# Generated by Django 3.1.6 on 2021-03-01 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils des utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': "Rôle d'utilisateur", 'verbose_name_plural': 'Rôles des utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='userstation',
            options={'verbose_name': 'Station pluviométrique', 'verbose_name_plural': 'Stations pluviométriques'},
        ),
    ]
