# Generated by Django 3.1.6 on 2021-02-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('normalized_name', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stations',
            field=models.ManyToManyField(blank=True, to='accounts.UserStations'),
        ),
    ]
