# Generated by Django 3.1.6 on 2021-02-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210207_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStations',
            new_name='UserStation',
        ),
    ]
