# Generated by Django 3.1.6 on 2021-03-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210314_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStation',
        ),
    ]
