# Generated by Django 3.1.6 on 2021-02-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('normalized_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recolt_type', models.BooleanField()),
                ('tilting_number', models.IntegerField()),
                ('tilting_date', models.DateField()),
                ('tilting_time', models.TimeField()),
                ('tilting_mm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mm_per_minute', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mm_per_hour', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mm_per_day', models.DecimalField(decimal_places=3, max_digits=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.station')),
            ],
        ),
    ]
