# Generated by Django 3.1.6 on 2021-03-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('normalized_name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('longitude', models.DecimalField(decimal_places=8, default=-72.285215, max_digits=13)),
                ('latitude', models.DecimalField(decimal_places=8, default=18.971187, max_digits=13)),
            ],
            options={
                'verbose_name': 'Station pluviométrique',
                'verbose_name_plural': 'Stations pluviométriques',
            },
        ),
        migrations.CreateModel(
            name='MeanYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_year', models.IntegerField()),
                ('mean_per_year', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Moyenne annuelle')),
                ('max_per_year', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Maximum annuel')),
                ('min_per_year', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Minimum annuel')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.station')),
            ],
            options={
                'verbose_name': 'Moyenne annuelle',
                'verbose_name_plural': 'Moyennes annuelles',
            },
        ),
        migrations.CreateModel(
            name='MeanWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_week', models.DateField()),
                ('mean_per_week', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Moyenne hebdomadaire')),
                ('max_per_week', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Maximum hebdomadaire')),
                ('min_per_week', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Minimum hebdomadaire')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.station')),
            ],
            options={
                'verbose_name': 'Moyenne hebdomadaire',
                'verbose_name_plural': 'Moyennes hebdomadaires',
            },
        ),
        migrations.CreateModel(
            name='MeanDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_day', models.DateField(verbose_name='Jour')),
                ('mean_per_day', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Moyenne journalière')),
                ('max_per_day', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Maximum journalier')),
                ('min_per_day', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Minimum journalier')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.station')),
            ],
            options={
                'verbose_name': 'Moyenne journalière',
                'verbose_name_plural': 'Moyennes journalières',
            },
        ),
        migrations.CreateModel(
            name='Intensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity_day', models.DateField()),
                ('duration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('start_interval', models.CharField(max_length=64, unique=True)),
                ('end_interval', models.CharField(max_length=64, unique=True)),
                ('intensity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.station')),
            ],
            options={
                'verbose_name': 'Intensité pluviométrique',
                'verbose_name_plural': 'Intensités pluviométriques',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilting_date', models.DateField(verbose_name='Date')),
                ('tilting_time', models.TimeField(verbose_name='Heure')),
                ('tilting_mm', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Mesure (en mm)')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.station')),
            ],
            options={
                'verbose_name': 'Donnée pluviométrique',
                'verbose_name_plural': 'Données pluviométriques',
            },
        ),
        migrations.AddConstraint(
            model_name='meanyear',
            constraint=models.UniqueConstraint(fields=('station', 'mean_year'), name='unique mean for a year'),
        ),
        migrations.AddConstraint(
            model_name='meanweek',
            constraint=models.UniqueConstraint(fields=('station', 'mean_week'), name='unique mean for a week'),
        ),
        migrations.AddConstraint(
            model_name='meanday',
            constraint=models.UniqueConstraint(fields=('station', 'mean_day'), name='unique mean for a day'),
        ),
        migrations.AddConstraint(
            model_name='intensity',
            constraint=models.UniqueConstraint(fields=('station', 'intensity_day', 'duration'), name='unique duration for a station and for a day'),
        ),
        migrations.AddConstraint(
            model_name='data',
            constraint=models.UniqueConstraint(fields=('station', 'tilting_date', 'tilting_time'), name='unique data value'),
        ),
    ]
