# Generated by Django 3.1.6 on 2021-03-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Donnée pluviométrique', 'verbose_name_plural': 'Données pluviométriques'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Station pluviométrique', 'verbose_name_plural': 'Stations pluviométriques'},
        ),
        migrations.RemoveField(
            model_name='data',
            name='mm_per_day',
        ),
        migrations.RemoveField(
            model_name='data',
            name='mm_per_hour',
        ),
        migrations.RemoveField(
            model_name='data',
            name='mm_per_minute',
        ),
        migrations.RemoveField(
            model_name='data',
            name='recolt_type',
        ),
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=18.971187, max_digits=13),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=-72.285215, max_digits=13),
        ),
        migrations.CreateModel(
            name='Mean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_day', models.DateField()),
                ('mean_per_day', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mean_per_week', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mean_per_year', models.DecimalField(decimal_places=3, max_digits=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.station')),
            ],
            options={
                'verbose_name': 'Moyenne pluviométrique',
                'verbose_name_plural': 'Moyennes pluviométriques',
            },
        ),
        migrations.CreateModel(
            name='Intensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity_day', models.DateField()),
                ('duration', models.TimeField()),
                ('max_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('start_interval', models.DecimalField(decimal_places=3, max_digits=10)),
                ('end_interval', models.DecimalField(decimal_places=3, max_digits=10)),
                ('intensity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.station')),
            ],
            options={
                'verbose_name': 'Intensité pluviométrique',
                'verbose_name_plural': 'Intensités pluviométriques',
            },
        ),
    ]
