# Generated by Django 3.1.6 on 2021-03-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210301_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='latiture',
            field=models.DecimalField(decimal_places=8, default=18.971187, max_digits=13),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=-72.285215, max_digits=13),
        ),
    ]
