# Generated by Django 3.1.6 on 2021-03-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210301_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='latiture',
            new_name='latitude',
        ),
    ]
